# Generated by Django 4.2.7 on 2023-11-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_Fase_proyecto',
            fields=[
                ('Id_fase', models.AutoField(primary_key=True, serialize=False)),
                ('Fase', models.CharField(max_length=100, verbose_name='Fase')),
            ],
        ),
        migrations.CreateModel(
            name='T_Gestion',
            fields=[
                ('Id_Ges', models.AutoField(primary_key=True, serialize=False)),
                ('Gestion', models.CharField(max_length=100, verbose_name='Nom_Gestion')),
            ],
        ),
        migrations.CreateModel(
            name='T_Materia',
            fields=[
                ('Id_Materia', models.AutoField(primary_key=True, serialize=False)),
                ('Materia', models.CharField(max_length=100, verbose_name='Materia')),
            ],
        ),
        migrations.CreateModel(
            name='T_Semestre',
            fields=[
                ('Id_Semestre', models.AutoField(primary_key=True, serialize=False)),
                ('Semestre', models.CharField(max_length=100, verbose_name='Semestre')),
            ],
        ),
        migrations.CreateModel(
            name='T_Tipo_Proyecto',
            fields=[
                ('Id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='T_Proyectos',
            fields=[
                ('Id_Proyect', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Finalizacion', models.DateField()),
                ('Descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('Documentacion', models.FileField(null=True, upload_to='Documento/', verbose_name='Documentacion')),
                ('Imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('T_Fase_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.t_fase_proyecto')),
                ('T_Gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.t_gestion')),
                ('T_Materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.t_materia')),
                ('T_Tipo_Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.t_tipo_proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='t_materia',
            name='T_Semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.t_semestre', verbose_name='Semestre'),
        ),
    ]
